default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  min_messages: WARNING

development:
  <<: *default
  database: nonriservato_dev

test:
  <<: *default
  database: nonriservato_test

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
